# Generated by Django 4.2.7 on 2023-12-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='offer',
            new_name='vacancy',
        ),
    ]
