# Generated by Django 5.0 on 2023-12-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_offer_quiz_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created']},
        ),
    ]
