# Generated by Django 5.0 on 2023-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_offer_quiz_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='devgrades',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=20),
        ),
    ]
