# Generated by Django 5.0 on 2023-12-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_vacancy_options_devgrades_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devgrades',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
