# Generated by Django 5.0 on 2023-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_devgrades_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
