# Generated by Django 5.0 on 2023-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_vacancy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
