# Generated by Django 5.0 on 2023-12-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_vacancy_options'),
        ('base', '0008_quizadditionalfield'),
    ]

    operations = [
    ]
